ThePrimeagen/harpoon

plugin/harpoon.vim
Fixed GotoBuffer to go to a terminal which
is already closed And made it vim compatible.
=> Fix gotobuffer

lua/harpoon/init.lua, plugin/manage-a-mark.vim, plugin/mark.vim
#4 should definitely be solved at this point
=> More nil work

lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua
Yes.  There was still more issues
=> fix again nil issues

lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua
Yes, we did it
And yes, its actual love potion.
#4
=> fix(issue-number-4): Like love potion # 9

lua/harpoon/init.lua
`get_config()` is removed and replaced by
`get_term_config()` and `get_mark_config()`
=> feat(save): remove dead code to prevent nil value on save

lua/harpoon/mark.lua
=> feat(quickfix)

lua/harpoon/mark.lua, lua/harpoon/ui.lua
BREAKING CHANGE:
- filter_nulls(list) renamed to filter_empty_string(list)
- swap(a, b) removed
- trim() removed
- promote() removed
- promote_to_front() removed
- remove_nils() removed
- shorten_list() removed
Fix #10
=> feat(mark)!: add set_current_at

lua/harpoon/mark.lua
@ThePrimeagen this PR adds file toggling and also updates rm_file to allow passing in the same arguments that add_file accepts.
=> Add file toggling

lua/harpoon/ui.lua
Fix #36
@ThePrimeagen @brandoncc Can you have a look, please test this before merge.
=> feat(ui): add BufWriteCmd to handle ":w" in quick menu

lua/harpoon/init.lua
=> fix the config having both expanded and non expanded

lua/harpoon/init.lua
Thank you for all the 🍐 's. They taste wonderful.
=> Fix clearing project config

README.md
Please refer to #61 for details, thank you! 🤗
=> Added plenary.nvim as an explicit dependency on docs

.stylua.toml, lua/harpoon/dev.lua, lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua, lua/harpoon/ui.lua, lua/harpoon/utils.lua
- used [stylua](https://github.com/JohnnyMorganz/StyLua) for consistent formatting
- all changes are non-functional
eventually have it as part of the CI process?
=> formatting with stylua

README.md, lua/harpoon/dev.lua, lua/harpoon/init.lua, plugin/mark.vim
Made a key appear on all the logs so its easy to read each sessions data
instead of one big ass-file
=> feat(logging): Enhanced the logging

.stylua.toml, lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua, lua/harpoon/ui.lua
=> fix(ui): Navigation with enter on menu

.luacheckrc, lua/harpoon/cmd-ui.lua, lua/harpoon/term.lua, lua/harpoon/test/manage_cmd_spec.lua
As discussed in #96 , this PR adds dynamic_commands feature to harpoon.
I have done some additions in harpoon.term module to provide API to add and remove commands.
I have added another module named harpoon.cmd-ui, this module intends to provide quick menu features like marks quick menu.
Sample usecase video link: https://youtu.be/oI4kMpkADI4
=> harpoon dynamic commands for projects

lua/harpoon/init.lua, lua/telescope/_extensions/harpoon.lua, lua/telescope/_extensions/marks.lua
closes #56
plan on trying to support all the current harpoon ui inside the telescope plugin
=> telescope extension

README.md
=> docs(navigation): added documentation for nav_next and nav_prev functions

README.md, TODO.md, lua/harpoon/cmd-ui.lua, lua/harpoon/dev.lua, lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua, lua/harpoon/tmux.lua, lua/harpoon/ui.lua, lua/harpoon/utils.lua, lua/telescope/_extensions/marks.lua
this is a 1st stepping stone in terms of #117, also better README :P
=> chore: project_cleanup

lua/harpoon/init.lua
I had the same issue #135 . For me, everything works fine with this patch
=> fix #135 "Attempt to index local 'projects' (a nil value)"

README.md
=> README: add an example showing how to configure the menu width

lua/telescope/_extensions/marks.lua
I saw this todo in the code so i implemented it.
PS: The formatting on lines 53-55 came from running `stylua lua/telescope/_extensions/marks.lua --config-path=.stylua.toml` so i assume it's alright?
=> Implement move up for telescope extension

README.md, lua/harpoon/init.lua
=> Open a harpoon file from the quickmenu in a vertical or horizontal split

README.md, lua/harpoon/init.lua, lua/harpoon/tabline.lua
Fixes:
https://github.com/ThePrimeagen/harpoon/issues/285
=> Tabline with harpoon items

README.md
Hey Prime,
thanks for building this!  
Made a tiny little tweak to the instructions in the README that weren't quite working for me.
`harpoon.ui:select(2)` didn't work, but `harpoon:list():select(2)`, and 3 and 4, ... did.
=> This fixes selecting file 2, 3, 4 for me

README.md, lua/harpoon/config.lua, lua/harpoon/ui.lua
Files can be opened in horizontal or vertical splits and in new tabs. Explanation on how to configure is added to the readme. Including work from name-snrl and Willothy.
=> Splits & tabs

README.md, lua/harpoon/config.lua, lua/harpoon/extensions/init.lua
=> feat: extensions for navigating to harpooned files

lua/harpoon/test/ui_spec.lua
Possibly solves #374. This is just an example for test I can write more of them if this one is ok.
=> test: add nvim_feedkeys test for ui
