lua/harpoon/mark.lua
I believe it was meant to swap the values in the same config
Someone reported this in discord
```
E5108: Error executing lua /home/peter/.vim/plugged/harpoon/lua/harpoon/mark.lua:51: attempt to index global 'mark_config' (a nil value)
```
=> undefined global mark_config

.editorconfig, lua/harpoon/dev.lua, lua/harpoon/mark.lua, lua/harpoon/ui.lua
This PR adds auto-saving of changes when the quick menu is closed. The implementation is very naive. It accepts any changes, and grabs the text after the first space in each line. No validations included.
I also added a .editorconfig and the dev reloader you helped me with.
=> Save changes when closing menu

lua/harpoon/ui.lua
This adds the harpoon filetype to the quick menu so that mappings can be setup specifically for use in the menu. Runonsentence+300points.
=> Set filetype for quick menu

lua/harpoon/mark.lua
This method can be used to display current mark status in the statusline.
Add the following in your init.vim:
```
hi User1 ctermfg=green guifg=green
function! HarpoonStatus() abort
return luaeval("require('harpoon.mark').status()")
endfunction
set statusline+=\ %1*%{HarpoonStatus()}
```
=> feat(mark): add status method

lua/harpoon/init.lua, lua/harpoon/ui.lua
Not sure if this is the proper way to solve this.
But my moving the son_menu_save call into the closing if-loop it will
get properly called on when closing the menu with toggle_quick_menu().
I think merging this change will resolve issue #49.
=> fix(ui): menusave now gets called on menu toggle

lua/harpoon/ui.lua
I assume it was used for debugging, but the config value was renamed so it prints `nil` every time the menu is opened.
=> remove print statement to a nonexistent value

lua/harpoon/term.lua
I've tested the following:
```
lua << EOF
require("harpoon").setup({
projects = {
["/home/asbjorn/devel/harpoon"] = {
term = {
cmds = {
"echo %s hello %s\n",
"echo this is item 2\n"
}
},
}
}
})
EOF
```
```
:lua require("harpoon.term").sendCommand(1, 1, "a", vim.fn.expand("%:p"))
:lua require("harpoon.term").sendCommand(1, 2)
```
Result:
```
[I] 21:12 [asbjorn@AH-XPS] /home/asbjorn/devel/harpoon [format_term_cmds] > echo a hello /home/asbjorn/devel/harpoon/README.md
a hello /home/asbjorn/devel/harpoon/README.md
[I] 21:12 [asbjorn@AH-XPS] /home/asbjorn/devel/harpoon [format_term_cmds] > echo this is item 2
this is item 2
```
=> feat(term): add string.format to term cmds

README.md, lua/harpoon/dev.lua, lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua, lua/harpoon/ui.lua
Here's my take on logging for #8. It uses the convenient `plenary.log` which writes a `harpoon.log` to `vim.fn.stdpath("cache")`.
By default the logging is enabled for `warning` and above. It can be changed with an env variable, e.g. when launching nvim `$ HARPOON_LOG=trace nvim` or setting `vim.g.harpoon_log_level` before requiring harpoon. I was considering harpoon's `global_setting` instead of the `vim.g`, but you'll get a recursive require if you want to log in `init.lua` then. Maybe there's some clever trick to get around this.
`warn` and `error` were assigned according to the existing print and error statements. Functions that users would directly interact with are `info`s, even just so that finding them in the logs is easier. Most other are `debug`. Local functions are assigned …
=> Add logging

lua/harpoon/ui.lua
It has it's limitations and can be improved.
Should we split the line `lua print(vim.fn.getline('.'))` on space and get the index?
Should we split the line and navigate with the path?
The path is safer if you haven't saved before hitting enter. Thoughts @ThePrimeagen ?
I quickly made this to better my workflow, but can adjust after settling the questions above.
The reasoning behind this is that I might have more marks than 4 marks, and I don't want to delete any.
Workspaces may solve the need for this, but I like that I can navigate with `enter` from normal mode.
=> feat(ui): navigate to mark on enter

.github/workflows/format.yml, .github/workflows/lint.yml, .luacheckrc, lua/harpoon/term.lua, lua/harpoon/test/manage-a-mark.lua
Tests are under a different issue (#30), so this one just deals with some ci action. closes #9
- add an action for
- linting with [luacheck](https://github.com/luarocks/luacheck)
- formatting check with previously added stylua
- commented out the test file stub, for now, to make the linter happy
- fleshed out getCmd function. wasn't sure what it's purpose was, but i didn't want to get rid of it
I also considered swapping out stylua for [luaFormatter](https://github.com/Koihik/LuaFormatter), to have both tools be luarocks based, but luaformatter creates some really funky looking code - it tries to inline too much or alternatively breaks everything onto a new line.
I also looked into [selene](https://github.com/Kampfkarren/selene) which, like stylua, is rust based, instead of using …
=> GH actions

lua/harpoon/ui.lua
According to the documentation for `vim.fn.bufnr` (`:h bufnr`), the
created buffer will have the option 'unlisted' by default.
This means that when navigating to a file, if that file wasn't
previously open, the new buffer won't appear in buffers list.
This fix set the buffer to be 'listed' when navigating.
=> fix(ui): Sets buffer as 'listed' when navigating

lua/harpoon/init.lua, lua/harpoon/mark.lua
setting a mark non-consecutively may result in `ensure_correct_config` trying to access nil values. `set_current_at` does fix the empty slots eventually, but before it does so, it calls `get_length` which calls `ensure_correct_config`.
It happens only sometimes due to how lua does memory allocation for arrays. Getting the length with `#` may or may not return the last index, depending on where the previous values are located.
---
Other:
some changes to log orders
=> prevent indexing nil vals in ensure_correct_config

README.md
Took me a while to figure out that it wouldn't work on nvim 0.4. Also, popup.nvim is required.
=> Add requirements missing in installation instructions

lua/harpoon/mark.lua
When using split windows, the mark status of the buffer in the active window was shown on every statusline. This change allows inactive windows to query the status with a buffer number to show a relevant index.
---
Also, `vim.fn.bufname()` uses current buffer by default, so it's identical to `vim.fn.bufname(vim.fn.bufnr())`
=> Allow statusline marks to differ between windows

lua/harpoon/term.lua
Adding the possibility for terminal handle to be something else than just pure shell.
For example `.gotoTerminal(2, ':e term://ipython')` and `.sendCommand(2, 'print(123)', ':e term://ipython')` ensures that the terminal one jumps to and send commands to, is an Ipython REPL.
=> custom terminal creation command

lua/harpoon/init.lua, lua/harpoon/mark.lua, lua/harpoon/term.lua, lua/harpoon/ui.lua
`vim.fn` functions are written in vimsciprt, while `vim.api` functions are written in  lua. Thus, `vim.api` functions tend to perform better.
=> moving from vim.fn to vim.api where possible

lua/harpoon/ui.lua
There's already a `save_on_change` global config option, but it doesn't currently do anything when changing text in the quick menu buffer (ie. reordering lines, etc). Just pouring some coconut oil on the old `save_on_change` option.
:tpope: :confession:
=> Hook up `save_on_change` option to menu buffer

lua/harpoon/term.lua
Added a function to simply clear/de-harpoon any previously harpooned terminals.
The terminals will still remain in the buffer pool but calling gotoTerminal will open up a fresh terminal.
Closes #91
First time contributing to anything but hope this is fine.
=> feat(term): add clear all functionality for terms

README.md, lua/harpoon/init.lua, lua/harpoon/term.lua
When sending a command to the terminal, I want it to immediately start running. This is a configuration implementation to allow for this use case.
=> feat(term): configuration to run command automatically on send

README.md, lua/harpoon/cmd-ui.lua, lua/harpoon/ui.lua
This removes popup.nvim as a dependency. Not so long ago, popup.nvim was moved into plenary and is planned to be archived later.
https://github.com/nvim-lua/plenary.nvim/pull/209
=> remove popup.nvim as dependency

lua/harpoon/cmd-ui.lua, lua/harpoon/ui.lua, lua/harpoon/utils.lua
Edited marks quick menu to use 'number' option instead of prefixing lines by indexes (which were no longer valid when reordering marks), in the same way as cmd quick menu.
Added 'q' and '\<ESC>' keymaps to cmd quick menu to close the window as in the marks quick menu.
And added \<CR> keymap to execute the command under the user's cursor (with a prompt to type the terminal index).
Closes #113
=> Quick menu improvements

README.md, lua/harpoon/init.lua, lua/harpoon/term.lua, lua/harpoon/tmux.lua, lua/harpoon/utils.lua
This PR introduces integrates Harpoon terminals and tmux.
- Adds module `harpoon.tmux`, which implements various functions that can be used to help Harpoon interact with `tmux`. The module implements the following functions for the user:
- `gotoTerminal`
- `sendCommand`
- `clear_all`
- and pretty much any and all functions implemented by the already implemented `term` module
- Adds a configuration option that closes all `tmux` windows generated by Harpoon on `nvim` close. This option is disabled by default (meaning any Harpoon-generated tmux windows stay open after `nvim` closes.
- I decided to implement the tmux functionality in a separate module, so that people have the option to choose between `harpoon.term` and `harpoon.tmux`.
- I've set it up so`harpoon.tmux` basically exactly mimics …
=> Add tmux support to Harpoon

lua/telescope/_extensions/marks.lua
This sets the `harpoon` `previewer` in `telescope` to show and highlight the exact location of the mark.
=> fix(telescope): use sorter and previewer from telescope settings

lua/harpoon/init.lua
As described in #68, the global HarpoonConfig of vim instance 2 does not
get updated if marks in vim instance 1 change, as described by
@freehaha.
This fix remedies the situation by refreshing marks for all other
projects before saving HarpoonConfig to disk.
=> fix #68 marks not saving due to over-writing by multiple vim instances

lua/harpoon/ui.lua
Harpoon is not able to differentiate between 2 files consistently using only the cwd path and
the filename.
as an example imagine you have a project with the following structure:
```lua
lua/plugins/init.lua
init.lua
```
both files are already marked by harpoon.
Opening `lua/plugins/init.lua` first, and then trying to jump
to `init.lua`, is not going to work, the bug happens since bufnr thinks that both files are the
same so it returns the same buffer number as `lua/plugins/init.lua`, which means a buffer is not
created, adding the full path prefix to the bufnr fixes this issue.
=> fixed inconsistent jumping between similarly named files

README.md, lua/harpoon/tmux.lua
Currently, it is not possible to pass an existing tmux pane ID to harpoon. This can be useful to run a terminal command in a split pane in the same window, for example. 
This PR adds the ability to execute commands like 
```lua
lua require("harpoon.tmux").gotoTerminal("{down-of}")   -- focus the pane directly below
lua require("harpoon.tmux").sendCommand("%3", "ls")     -- send a command to the pane with id '%3'
```
=> Add ability to pass any tmux pane identifier

lua/harpoon/init.lua, lua/harpoon/utils.lua
When jumping from one feature branch to another with git, I struggled with the fact that Harpoon only saved my marked files based on the current project. However, for every feature, I need to change code in different files corresponding to the feature (which I want to be marked).
With this PR, I changed the behaviour to make sure every branch in the project has its own marks. Each project still has its general terminal commands which I can configure and use over the different branches.
Toggle this feature with a `mark_branch` property in harpoon settings.
Example:
```lua
require("harpoon").setup({
mark_branch = true,
projects = {
["$HOME/Developer/your-project"] = {
term = {
cmds = {
"docker exec -it web bash",
}
}
}
}
})
```
=> Add mark functionality per git branch

lua/harpoon/tmux.lua
It seems that `tmux` has recently made changes to the way some of their commands give output. Since Harpoon depends on some of those commands for the `harpoon.tmux` module, some changes were necessary to allow this to work.
=> fix(tmux): fix tmux module to comply with latest changes to tmux API

lua/harpoon/ui.lua
If the filename is an absolute path then there is no need to
prepend the path with the current directory.
Detect absolute paths and open them as-is.
This fixes harpoon when editing files through symlinks
that point to other places on the filesystem.
=> harpoon.ui: handle absolute paths

README.md, lua/harpoon/init.lua, lua/harpoon/utils.lua
A few changes from #98 
1. Use `git rev-parse --abbrev-ref HEAD` over `git branch --show-current` as it's more commonly available on old git versions.
2. Reduced the number of calls to the aforementioned command to improve performance
3. Make `mark_branch` a global_setting
4. Add `mark_branch` under global_settings in README
=> refactor: improve git branch specific marks impl

lua/harpoon/tmux.lua
gotoTerminal should work for both the pane and window case.
Resolves #158
=> Fix tmux gotoTerminal for panes

lua/harpoon/ui.lua
I'm not perfectly sure if this should be upstreamed, but seems like passing true to bufnr `create` argument now fails.
This fixes this issue by adding a new buffer with bufadd when the buffer does not exist in the buffer list.
The issue can be reproduced as follow:
- open a project, add a mark to a file
- close the project
- reopen the project
- open harpoon ui
- try to navigate to the marked file
You should get something like:
```
E5108: Error executing lua Vim:E94: No matching buffer for FILE
stack traceback:
[C]: in function 'bufnr'
...e/nvim/site/pack/packer/start/harpoon/lua/harpoon/ui.lua:171: in function 'nav_file
'
...e/nvim/site/pack/packer/start/harpoon/lua/harpoon/ui.lua:150: in function 'select_m
enu_item'
[string ":lua"]:1: in main chunk
```
=> fix(nav-file): bufnr failure when trying to create the buffer

lua/harpoon/init.lua, lua/harpoon/tmux.lua, lua/harpoon/utils.lua
Fixes files in the master branch that were not formatted correctly. This caused the stylua format action to fail on every PR submitted, which at a glance could mislead maintainers to think it was the fault of the PR. Hopefully this will reduce the friction a bit for contribution.
=> Formatted failing files

lua/harpoon/init.lua, lua/harpoon/mark.lua
I'm hoping to use this PR to make a few performance improvements.
The first commit is a minor performance improvement to speed up buffer switching. The culprit is [this call](https://github.com/ThePrimeagen/harpoon/blob/f4aff5bf9b512f5a85fe20eb1dcf4a87e512d971/lua/harpoon/init.lua#L20) to `store_offset()` which is setup as a `BufLeave` autocmd. It loops through all harpoon marks to find a match for the current buffer, and stores the cursor's row + column position for that mark, all before leaving the buffer. The more marks we add, the more marks we have to loop through when buffer switching. This commit moves the `get_mark_config()` call outside our loop which marginally improves buffer switching performance.
Will try to dig into other optimizations like a faster JSON parser or anything …
=> Performance improvements 

lua/harpoon/ui.lua
This PR contains two changes that revolve around a single purpose - to make the currently opened file easily noticeable in the quick menu.
The first one is non-breaking and it adds a highlight group (`HarpoonCurrentFile`, not linked by default) on the line that contains the currently opened file.
The second is somewhat breaking and moves the cursor to the line that contains the currently opened file when you open the quick menu.
If the current buffer is not Harpooned, they do nothing.
Here's a preview to help explain the features.
[Peek 2022-08-23 22-40.webm](https://user-images.githubusercontent.com/543561/186251943-0021f2f3-fe6c-48a7-9277-94dff3dc55e9.webm)
(Here, `HarpoonCurrentFile` is linked to Search - `:highlight link HarpoonCurrentFile Search`)
Rationale: In the couple of months …
=> feat: Make current file easily noticeable

lua/telescope/_extensions/marks.lua
This PR updates the `telescope` extension's `results` and `entry_maker` config options. This resolves the issue where the mark/result/entry index is `nil` (see #242 ). In addition, it renames `filter_empty_string` to `prepare_results` to be more descriptive.
Before:
After:
=> Fix nil in index column for telescope extension

lua/harpoon/ui.lua
I have an annoying experience every time I navigate to one of my harpoon files right after launching vim that roughly goes as follows:
- Launch vim (opens empty buffer)
- Navigate to first harpoon file (opens file, leaves empty buffer loaded)
- Switch back to empty unnamed buffer
- Delete empty unnamed buffer
This change addresses this issue by adding a few lines of code to check whether the current  buffer before navigating is an empty unnamed buffer and deletes it after navigation:
- Launch vim (opens empty buffer)
- Navigate to first harpoon file (opens file, deletes empty buffer)
=> Remove empty `[No Name]` buffer when navigating to file.

lua/harpoon/utils.lua
There's a noticeable slowdown when opening the quick menu or switching to a file when `mark_branch` is enabled. It's present even on modern hardware with a fast ssd. Barely noticeable but still enough to destroy that creamy-smooth harpoon feel.
I've identified the cause of the slowdown to be the call to the `git` binary when getting the branch name.
Given the ubiquity of tpope's `vim-fugitive`, I've used `FugitiveHead` to get the branch name. It doesn't rely on the `git` binary so it's noticeably faster.  It's not a hard dependency, so when fugitive is not available, it falls back to the current method - calling `git rev-parse`.
=> Use fugitive for faster branch name resolution

lua/harpoon/init.lua
After https://github.com/neovim/neovim/pull/25523 the comma separated events are not valid any more and will throw error
=> fix: events no longer can be comma separated

lua/harpoon/init.lua
Apparently this is what the cool plugin devs do :smiley:
Proof:
- [Telescope](https://github.com/nvim-telescope/telescope.nvim/blob/3f5f165447d797576206e3b9bd555ea8db85b6f2/plugin/telescope.lua#L94)
- [Lazy](https://github.com/folke/lazy.nvim/blob/96584866b9c5e998cbae300594d0ccfd0c464627/lua/lazy/view/colors.lua#L42)
- [Mason](https://github.com/williamboman/mason.nvim/blob/41e75af1f578e55ba050c863587cffde3556ffa6/lua/mason/ui/colors.lua#L27)
- [Neogit](https://github.com/NeogitOrg/neogit/blob/d0e87541130b2cf62d7f8a54487ef99560232fb6/lua/neogit/lib/hl.lua#L204)
=> feat: link harpoon highlights to default groups

README.md, lua/harpoon/buffer.lua, lua/harpoon/config.lua, lua/harpoon/init.lua, lua/harpoon/list.lua, lua/harpoon/ui.lua
These maybe should have been separate PRs, but they're all small changes and somewhat related so I made them all at once. If you want me to split this up, let me know. There are also some overlapping changes with #386, so I can remove that functionality from this PR if that one is preferred.
- fix: ensure buf is loaded on select (#383, #377)
- fix: remove angle brackets from Escape mapping rhs (#379, #385)
- fix: incorrect function call in run_toggle_command (#379)
- fix: use buf-local autocmds
- refactor: use Lua API to create BufModifiedSet autocmd
- fix: sync when list is resolved (mentioned in #386)
- fix: check displayed list to find removed items in `HarpoonList:resolve_displayed()` (fixes remove events not being dispatched when saving from the menu)
- fix: pass item objects to …
=> fix(ui): comprehensive UI and sync fixes

lua/harpoon/list.lua, lua/harpoon/listeners.lua
Anotha one
Adds a `move` event so we can have similar tracking to v1's `harpoon.on("changed", ...)`. I use the event to trigger reordering of buffers in my tabline according to their order in harpoon (falling back to standard buffer order for non-marked bufs).
=> feat: introduce move event

lua/harpoon/buffer.lua, lua/harpoon/config.lua, lua/harpoon/test/utils.lua, lua/harpoon/ui.lua
Replaces uses of `nvim_buf_set_option`, which is deprecated, with `nvim_set_option_value`
=> refactor: remove uses of deprecated `buf_set_option`

lua/harpoon/config.lua, lua/harpoon/init.lua
Fixes lists that don't encode by checking if `list.config.encode` is nil instead of checking `list.encode` (which will never be nil).
Also actually defaults `save_on_toggle` to true, because it says it defaults to true in several places (it also says false in some places? idk) and harpoon basically doesn't work without it unless `sync_on_ui_close` is enabled.
=> fix: check list.config.encode, default save_on_toggle to false

lua/harpoon/ui.lua
This is related to #402.
This let's you revert back some of the UI looks.
```lua
local harpoon = require('harpoon')
harpoon.ui:toggle_quick_menu(harpoon:list()), { border = "rounded", title_pos = "center" })
```
=> feat(ui): accept title_pos option if specified

.github/workflows/ci.yml, .github/workflows/lint.yml, Makefile, scripts/tests/minimal.vim
Fixes the CI runs by adding the dependencies needed to run the test
Also includes a minimal init to scaffold a working neovim
uses minimal init's from here: https://github.com/nvim-lua/nvim-lua-plugin-template
additionally, I had to remove the mac testing as I couldn't get it to pass due to /tmp /private/tmp mapping issues
Example:
```
Fail	||	config default.create_list_item	
...er/work/harpoon/harpoon/lua/harpoon/test/config_spec.lua:21: Expected objects to be the same.
Passed in:
(table: 0x010e17a148) {
[context] = {
[col] = 1
[row] = 3 }
*[value] = '/tmp/harpoon-test' }
Expected:
(table: 0x010e17a0b8) {
[context] = {
[col] = 1
[row] = 3 }
*[value] = '/private/tmp/harpoon-test' }
```
Full run details: https://github.com/tris203/harpoon/actions/runs/7234139487
I tried a couple of things, …
=> ci: fix ci

README.md
Added previous and next documentation to configuration in README for Harpoon2.
I realized I used my preference for shortcuts, happy to update to the suggested for Harpoon 1
=> Add documentation to readme for previous and next shortcuts
